# Generated by Django 4.2 on 2026-05-20 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_visionmetric_timestamp_default'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visionmetric',
            name='core_vision_ts_zone_idx',
        ),
        migrations.AddField(
            model_name='token',
            name='medical_notes',
            field=models.TextField(blank=True, help_text='Additional tests needed, disease history, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='visionmetric',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
