# Generated by Django 4.2 on 2026-06-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_token_one_in_progress_per_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20),
        ),
    ]
