/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as QueuesRouteImport } from './routes/queues'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as DisplayRouteImport } from './routes/display'
import { Route as CctvRouteImport } from './routes/cctv'
import { Route as IndexRouteImport } from './routes/index'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesRoute = QueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayRoute = DisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => rootRouteImport,
} as any)
const CctvRoute = CctvRouteImport.update({
  id: '/cctv',
  path: '/cctv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cctv': typeof CctvRoute
  '/display': typeof DisplayRoute
  '/notifications': typeof NotificationsRoute
  '/queues': typeof QueuesRoute
  '/staff': typeof StaffRoute
  '/system': typeof SystemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cctv': typeof CctvRoute
  '/display': typeof DisplayRoute
  '/notifications': typeof NotificationsRoute
  '/queues': typeof QueuesRoute
  '/staff': typeof StaffRoute
  '/system': typeof SystemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cctv': typeof CctvRoute
  '/display': typeof DisplayRoute
  '/notifications': typeof NotificationsRoute
  '/queues': typeof QueuesRoute
  '/staff': typeof StaffRoute
  '/system': typeof SystemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cctv'
    | '/display'
    | '/notifications'
    | '/queues'
    | '/staff'
    | '/system'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cctv'
    | '/display'
    | '/notifications'
    | '/queues'
    | '/staff'
    | '/system'
  id:
    | '__root__'
    | '/'
    | '/cctv'
    | '/display'
    | '/notifications'
    | '/queues'
    | '/staff'
    | '/system'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CctvRoute: typeof CctvRoute
  DisplayRoute: typeof DisplayRoute
  NotificationsRoute: typeof NotificationsRoute
  QueuesRoute: typeof QueuesRoute
  StaffRoute: typeof StaffRoute
  SystemRoute: typeof SystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues': {
      id: '/queues'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof QueuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display': {
      id: '/display'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cctv': {
      id: '/cctv'
      path: '/cctv'
      fullPath: '/cctv'
      preLoaderRoute: typeof CctvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CctvRoute: CctvRoute,
  DisplayRoute: DisplayRoute,
  NotificationsRoute: NotificationsRoute,
  QueuesRoute: QueuesRoute,
  StaffRoute: StaffRoute,
  SystemRoute: SystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
